/**
 * shieldcn
 * app/api/migrate/pr/route
 *
 * POST — Create a PR replacing shields.io badges with shieldcn badges.
 *
 * Body: {
 *   owner: string,
 *   repo: string,
 *   readmePath: string,
 *   readmeSha: string,
 *   transformedContent: string,
 *   badgeCount: number,
 * }
 *
 * Returns: { prUrl, prNumber }
 */

import { NextRequest, NextResponse } from "next/server"
import {
  getInstallationForRepo,
  getInstallationToken,
  gh,
} from "../github-app"
import { trackEvent } from "@/lib/openpanel"
import { checkRateLimit, getClientIdentifier } from "@shieldcn/core/rate-limit"

export async function POST(req: NextRequest) {
  if (!process.env.GITHUB_APP_ID) {
    return NextResponse.json(
      { error: "Migration tool not configured" },
      { status: 503 },
    )
  }

  const limit = await checkRateLimit("migrate-pr", getClientIdentifier(req), { max: 25, windowMs: 60 * 60_000 })
  if (!limit.allowed) {
    return NextResponse.json(
      { error: "Too many migration PRs. Try again later." },
      { status: 429, headers: { "Retry-After": String(Math.ceil(limit.resetMs / 1000)) } },
    )
  }

  const body = await req.json()
  const { owner, repo, readmePath, readmeSha, transformedContent, badgeCount } =
    body

  if (!owner || !repo || !readmePath || !readmeSha || !transformedContent) {
    return NextResponse.json(
      { error: "Missing required fields" },
      { status: 400 },
    )
  }

  try {
    // 1. Get installation
    const installationId = await getInstallationForRepo(owner, repo)
    if (!installationId) {
      return NextResponse.json(
        { error: "App not installed on this repo" },
        { status: 403 },
      )
    }

    const token = await getInstallationToken(installationId, owner, repo)

    // 2. Get default branch
    const repoData = await gh(token, `/repos/${owner}/${repo}`)
    const defaultBranch = repoData.default_branch || "main"

    // 3. Get HEAD sha
    const ref = await gh(
      token,
      `/repos/${owner}/${repo}/git/ref/heads/${defaultBranch}`,
    )
    const headSha = ref.object.sha

    // 4. Create branch
    const branchName = `shieldcn/migrate-badges-${Date.now().toString(36)}`
    await gh(token, `/repos/${owner}/${repo}/git/refs`, {
      method: "POST",
      body: JSON.stringify({
        ref: `refs/heads/${branchName}`,
        sha: headSha,
      }),
    })

    // 5. Update README on the branch
    await gh(token, `/repos/${owner}/${repo}/contents/${readmePath}`, {
      method: "PUT",
      body: JSON.stringify({
        message: "chore: migrate shields.io badges to shieldcn",
        content: Buffer.from(transformedContent).toString("base64"),
        sha: readmeSha,
        branch: branchName,
      }),
    })

    // 6. Open PR
    const prBody = [
      "## 🛡️ Migrate badges to shieldcn",
      "",
      `This PR replaces **${badgeCount || "all"} shields.io badge${badgeCount === 1 ? "" : "s"}** with [shieldcn](https://shieldcn.dev) equivalents.`,
      "",
      "### What is shieldcn?",
      "",
      "shieldcn renders GitHub README badges as shadcn/ui Button components — 6 variants, 16 themes, 40,000+ icons, dark/light mode support.",
      "",
      "### What changed",
      "",
      `Badge image URLs in \`${readmePath}\` were updated from \`img.shields.io\` to \`shieldcn.dev\`. The badge data (stars, version, downloads, etc.) is the same — only the rendering service changed.`,
      "",
      "### Customization",
      "",
      "You can customize any badge by adding query parameters:",
      "",
      "| Param | Example | Description |",
      "|-------|---------|-------------|",
      "| `variant` | `?variant=branded` | `default`, `secondary`, `outline`, `ghost`, `branded` |",
      "| `mode` | `?mode=light` | `dark` or `light` |",
      "| `theme` | `?theme=blue` | 16 color themes |",
      "| `size` | `?size=default` | `xs`, `sm`, `default`, `lg` |",
      "| `logo` | `?logo=react` | Override icon (2400+ SimpleIcons + 40k React Icons) |",
      "",
      "See the [full docs](https://shieldcn.dev/docs) for all options.",
      "",
      "---",
      "",
      "*Generated by the [shieldcn migration tool](https://shieldcn.dev/migrate).*",
    ].join("\n")

    const pr = await gh(token, `/repos/${owner}/${repo}/pulls`, {
      method: "POST",
      body: JSON.stringify({
        title: "chore: migrate shields.io badges to shieldcn",
        body: prBody,
        head: branchName,
        base: defaultBranch,
      }),
    })

    void trackEvent({
      name: "migrate_pr_created",
      data: {
        owner,
        repo,
        badgeCount: badgeCount || 0,
        prNumber: pr.number,
      },
    })

    return NextResponse.json({
      success: true,
      prUrl: pr.html_url,
      prNumber: pr.number,
    })
  } catch (err) {
    console.error("Migration PR error:", err)
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Failed to create PR" },
      { status: 500 },
    )
  }
}
